### PR TITLE
Fix API call to removeChunk.

### LINKED ISSUE #66: Undefined remove method
There is a call to an undefined method `remove` in `https.js`.

https://github.com/digitalbazaar/bedrock-edv-storage/blob/9e40f0cfea6aae6edc8ece7cdf1f485636787e11/lib/http.js#L441

This appears to be a typo as the correct method in `storage.js` is named `removeChunk`
https://github.com/digitalbazaar/bedrock-edv-storage/blob/9e40f0cfea6aae6edc8ece7cdf1f485636787e11/lib/storage.js#L580-L590

Along with this, a unit test for document chunk deletion should be added.

### PR DESCRIPTION
**Pull request by mattcollier**
Fixes #66.

### CODE REVIEW

**Review by JSAssassin — APPROVED** [review]
LGTM, thank you.

**Comment by mattcollier** [comment]
@JSAssassin are you aware of any unit test or manual tests we can do to test this removeChunk codepath which apparently has never been used before?

**Comment by JSAssassin** [comment]
@mattcollier nope, there are some streams tests in edv-client though https://github.com/digitalbazaar/edv-client/blob/master/tests/30-EdvStreams.spec.js, not sure if that's helpful.

**Comment by aljones15** [comment]
> @mattcollier nope, there are some streams tests in edv-client though https://github.com/digitalbazaar/edv-client/blob/master/tests/30-EdvStreams.spec.js, not sure if that's helpful.

@JSAssassin @mattcollier I added an issue here: https://github.com/digitalbazaar/bedrock-edv-storage/issues/68

we need to decide on who is going to add these tests. the ones from edv client should be portable, but might require some work.

**Review by dlongley — APPROVED** [review]
Thanks!

**Pull request merged**
